### ISSUE TITLE
I was looking for this!

### ISSUE THREAD

**Issue by nilsbyte** [KingIzzymon/DeckyPlugin-MagicPacket#1]
@KingIzzymon You had the same idea as me. Looks like you did not continue development? I cant find the plugin in the testing store. What's the status of your plugin? Are you planning on working on it? :)

**Comment by KingIzzymon** [comment]
@nilsbyte I actually stopped because I spoke with the developer of the Moonlight plugin and he already did it lol sorry, I meant to remove this project from my account

**Comment by nilsbyte** [comment]
well :D i see. The Moonlight plugin is to bloated for just WoL, dont want to use it. Sad.
